# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='state',
            field=models.IntegerField(choices=[(4, 'On the bench'), (8, 'Gone home'), (0, 'On the court')], default=8),
        ),
    ]
