# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20151224_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='state',
            field=models.IntegerField(choices=[(0, 'On the court'), (8, 'Gone home'), (4, 'On the bench')], default=8),
        ),
    ]
