language: python
python:
- '3.8'
dist: xenial
env:
  global:
    - MOZ_HEADLESS=1
addons:
  firefox: latest
services:
- postgresql
- xvfb
script:
- coverage run --source=core,groups manage.py test
after_success:
- codecov
