language: python
python:
  - "3.5"
install:
  - pip install -r requirements/run.txt
  - pip install -r requirements/test.txt
  - pip install coveralls
script:
  - coverage run --source=groups,core manage.py test functional_tests
# Running a display for selenium firefox driver
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
after_success:
  coveralls
